///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDatabaseTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDatabaseTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("558d6956-a12d-4102-ae72-579bfe35899a")]
    public partial class RxDatabaseTestRepository : RepoGenBaseFolder
    {
        static RxDatabaseTestRepository instance = new RxDatabaseTestRepository();
        RxDatabaseTestRepositoryFolders.VirginMediaOfficialSiteAppFolder _virginmediaofficialsite;
        RxDatabaseTestRepositoryFolders.VirginMediaMyVirginMediaAppFolder _virginmediamyvirginmedia;
        RxDatabaseTestRepositoryFolders.VirginMediaBusinessBusinessAndPubAppFolder _virginmediabusinessbusinessandpub;
        RxDatabaseTestRepositoryFolders.VirginMediaOfficialSiteInternetAppFolder _virginmediaofficialsiteinternet;
        RxDatabaseTestRepositoryFolders.YahooLoginAppFolder _yahoologin;
        RxDatabaseTestRepositoryFolders.YahooMailAppFolder _yahoomail;
        RxDatabaseTestRepositoryFolders.YahooUKNewsEmailAndSearchInteAppFolder _yahoouknewsemailandsearchinte;

        /// <summary>
        /// Gets the singleton class instance representing the RxDatabaseTestRepository element repository.
        /// </summary>
        [RepositoryFolder("558d6956-a12d-4102-ae72-579bfe35899a")]
        public static RxDatabaseTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDatabaseTestRepository() 
            : base("RxDatabaseTestRepository", "/", null, 0, false, "558d6956-a12d-4102-ae72-579bfe35899a", ".\\RepositoryImages\\RxDatabaseTestRepository558d6956.rximgres")
        {
            _virginmediaofficialsite = new RxDatabaseTestRepositoryFolders.VirginMediaOfficialSiteAppFolder(this);
            _virginmediamyvirginmedia = new RxDatabaseTestRepositoryFolders.VirginMediaMyVirginMediaAppFolder(this);
            _virginmediabusinessbusinessandpub = new RxDatabaseTestRepositoryFolders.VirginMediaBusinessBusinessAndPubAppFolder(this);
            _virginmediaofficialsiteinternet = new RxDatabaseTestRepositoryFolders.VirginMediaOfficialSiteInternetAppFolder(this);
            _yahoologin = new RxDatabaseTestRepositoryFolders.YahooLoginAppFolder(this);
            _yahoomail = new RxDatabaseTestRepositoryFolders.YahooMailAppFolder(this);
            _yahoouknewsemailandsearchinte = new RxDatabaseTestRepositoryFolders.YahooUKNewsEmailAndSearchInteAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("558d6956-a12d-4102-ae72-579bfe35899a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The VirginMediaOfficialSite folder.
        /// </summary>
        [RepositoryFolder("da0e99d9-f0ce-4ba9-ba9a-8c9792248f87")]
        public virtual RxDatabaseTestRepositoryFolders.VirginMediaOfficialSiteAppFolder VirginMediaOfficialSite
        {
            get { return _virginmediaofficialsite; }
        }

        /// <summary>
        /// The VirginMediaMyVirginMedia folder.
        /// </summary>
        [RepositoryFolder("2d3ecc95-4379-4ad1-9cd7-1ee55a5a99b1")]
        public virtual RxDatabaseTestRepositoryFolders.VirginMediaMyVirginMediaAppFolder VirginMediaMyVirginMedia
        {
            get { return _virginmediamyvirginmedia; }
        }

        /// <summary>
        /// The VirginMediaBusinessBusinessAndPub folder.
        /// </summary>
        [RepositoryFolder("4182e6ef-4ad1-4039-81f8-5be2df6354a6")]
        public virtual RxDatabaseTestRepositoryFolders.VirginMediaBusinessBusinessAndPubAppFolder VirginMediaBusinessBusinessAndPub
        {
            get { return _virginmediabusinessbusinessandpub; }
        }

        /// <summary>
        /// The VirginMediaOfficialSiteInternet folder.
        /// </summary>
        [RepositoryFolder("64541cbd-0120-4185-8052-27ab8d8751d6")]
        public virtual RxDatabaseTestRepositoryFolders.VirginMediaOfficialSiteInternetAppFolder VirginMediaOfficialSiteInternet
        {
            get { return _virginmediaofficialsiteinternet; }
        }

        /// <summary>
        /// The YahooLogin folder.
        /// </summary>
        [RepositoryFolder("bca39131-1b42-431e-a5ff-877e444ff632")]
        public virtual RxDatabaseTestRepositoryFolders.YahooLoginAppFolder YahooLogin
        {
            get { return _yahoologin; }
        }

        /// <summary>
        /// The YahooMail folder.
        /// </summary>
        [RepositoryFolder("ead32e73-8d7a-44f2-a791-3bc5fe8ae9e4")]
        public virtual RxDatabaseTestRepositoryFolders.YahooMailAppFolder YahooMail
        {
            get { return _yahoomail; }
        }

        /// <summary>
        /// The YahooUKNewsEmailAndSearchInte folder.
        /// </summary>
        [RepositoryFolder("471d34d2-0e13-4351-8740-590f8401d9b9")]
        public virtual RxDatabaseTestRepositoryFolders.YahooUKNewsEmailAndSearchInteAppFolder YahooUKNewsEmailAndSearchInte
        {
            get { return _yahoouknewsemailandsearchinte; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class RxDatabaseTestRepositoryFolders
    {
        /// <summary>
        /// The VirginMediaOfficialSiteAppFolder folder.
        /// </summary>
        [RepositoryFolder("da0e99d9-f0ce-4ba9-ba9a-8c9792248f87")]
        public partial class VirginMediaOfficialSiteAppFolder : RepoGenBaseFolder
        {
            RxDatabaseTestRepositoryFolders.ContainerFluidFolder _containerfluid;
            RepoItemInfo _myvirginmediaInfo;
            RepoItemInfo _broadbandonlyInfo;
            RepoItemInfo _m100fibrebroadbandInfo;

            /// <summary>
            /// Creates a new VirginMediaOfficialSite  folder.
            /// </summary>
            public VirginMediaOfficialSiteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VirginMediaOfficialSite", "/dom[@domain='www.virginmedia.com']", parentFolder, 30000, null, false, "da0e99d9-f0ce-4ba9-ba9a-8c9792248f87", "")
            {
                _containerfluid = new RxDatabaseTestRepositoryFolders.ContainerFluidFolder(this);
                _myvirginmediaInfo = new RepoItemInfo(this, "MyVirginMedia", ".//div[#'unified-header']/div/div/div[2]/div[1]/div[3]/ul/li[2]/a[@innertext='My Virgin Media    ']", 30000, null, "142d9fa3-95fb-46ac-8c7e-b261e4938345");
                _broadbandonlyInfo = new RepoItemInfo(this, "Broadbandonly", ".//div[#'df1263DesktopContainer']/div/div/div/div/div/div/div[4]/a[@href~'^https://www\\.virginmedia\\.c']/div[2]/p[@innertext='Broadbandonly']", 30000, null, "5efeafce-6d24-4a1a-ba27-102a4d0e45a9");
                _m100fibrebroadbandInfo = new RepoItemInfo(this, "M100FibreBroadband", ".//div[#'mainPageContent']/section/div/div[13]/div/div/div[2]/div/div/div/div[2]/div/div/div[2]/?/?/h3[@innertext='M100Fibre Broadband']", 30000, null, "7ff7489d-762f-445a-98b0-56741a916eea");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("da0e99d9-f0ce-4ba9-ba9a-8c9792248f87")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("da0e99d9-f0ce-4ba9-ba9a-8c9792248f87")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MyVirginMedia item.
            /// </summary>
            [RepositoryItem("142d9fa3-95fb-46ac-8c7e-b261e4938345")]
            public virtual Ranorex.ATag MyVirginMedia
            {
                get
                {
                    return _myvirginmediaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MyVirginMedia item info.
            /// </summary>
            [RepositoryItemInfo("142d9fa3-95fb-46ac-8c7e-b261e4938345")]
            public virtual RepoItemInfo MyVirginMediaInfo
            {
                get
                {
                    return _myvirginmediaInfo;
                }
            }

            /// <summary>
            /// The Broadbandonly item.
            /// </summary>
            [RepositoryItem("5efeafce-6d24-4a1a-ba27-102a4d0e45a9")]
            public virtual Ranorex.PTag Broadbandonly
            {
                get
                {
                    return _broadbandonlyInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Broadbandonly item info.
            /// </summary>
            [RepositoryItemInfo("5efeafce-6d24-4a1a-ba27-102a4d0e45a9")]
            public virtual RepoItemInfo BroadbandonlyInfo
            {
                get
                {
                    return _broadbandonlyInfo;
                }
            }

            /// <summary>
            /// The M100FibreBroadband item.
            /// </summary>
            [RepositoryItem("7ff7489d-762f-445a-98b0-56741a916eea")]
            public virtual Ranorex.H3Tag M100FibreBroadband
            {
                get
                {
                    return _m100fibrebroadbandInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The M100FibreBroadband item info.
            /// </summary>
            [RepositoryItemInfo("7ff7489d-762f-445a-98b0-56741a916eea")]
            public virtual RepoItemInfo M100FibreBroadbandInfo
            {
                get
                {
                    return _m100fibrebroadbandInfo;
                }
            }

            /// <summary>
            /// The ContainerFluid folder.
            /// </summary>
            [RepositoryFolder("6449d789-f3cc-48fe-8a63-e8f5ba41a842")]
            public virtual RxDatabaseTestRepositoryFolders.ContainerFluidFolder ContainerFluid
            {
                get { return _containerfluid; }
            }
        }

        /// <summary>
        /// The ContainerFluidFolder folder.
        /// </summary>
        [RepositoryFolder("6449d789-f3cc-48fe-8a63-e8f5ba41a842")]
        public partial class ContainerFluidFolder : RepoGenBaseFolder
        {
            VirginMediaInfoClass _virginmediaInfo;
            RepoItemInfo _findastoreInfo;
            RepoItemInfo _expandingournetworkInfo;
            RepoItemInfo _forbusinessInfo;
            RepoItemInfo _helpInfo;

            /// <summary>
            /// Creates a new ContainerFluid  folder.
            /// </summary>
            public ContainerFluidFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerFluid", ".//div[#'unified-header']/div/div", parentFolder, 30000, null, false, "6449d789-f3cc-48fe-8a63-e8f5ba41a842", "")
            {
                _virginmediaInfo = new VirginMediaInfoClass(this);
                _findastoreInfo = new RepoItemInfo(this, "FindAStore", "div[2]/div[1]/div[1]/ul/li[2]/a[@innertext='Find a store    ']", 30000, null, "a5750005-6ef7-4f3e-98c3-47ee3a2413ed");
                _expandingournetworkInfo = new RepoItemInfo(this, "ExpandingOurNetwork", "div[2]/div[1]/div[3]/ul/li[3]/a[@innertext~'^Expanding\\ our\\ network\\ \\ \\ ']", 30000, null, "c0083344-eaba-4085-9513-9840c6dabf9e");
                _forbusinessInfo = new RepoItemInfo(this, "ForBusiness", "div[2]/div[1]/div[3]/ul/li[5]/a[@innertext='For business    ']", 30000, null, "c4cbcd82-30c2-4271-8596-10fa591f4520");
                _helpInfo = new RepoItemInfo(this, "Help", "div[2]/div[1]/div[3]/ul/li[4]/a[@innertext='Help    ']", 30000, null, "729e15b1-2fc9-42c9-996e-6e5e72617efa");
            }

            /// <summary>
            /// The VirginMediaInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("dd472150-7887-44de-b6ee-daa70cff6438")]
            public class VirginMediaInfoClass : RepoItemInfo
            {
                /// <summary>
                /// VirginMediaInfoClass class constructor.
                /// </summary>
                public VirginMediaInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "VirginMedia", "div[1]/a[@href~'^https://www\\.virginmedia\\.c']/?/?/img[@alt='Virgin Media']", 30000, null, "dd472150-7887-44de-b6ee-daa70cff6438")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("cec3e525-d844-41ab-9c37-64b09f2bc060")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("cec3e525-d844-41ab-9c37-64b09f2bc060");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("cec3e525-d844-41ab-9c37-64b09f2bc060")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("cec3e525-d844-41ab-9c37-64b09f2bc060", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6449d789-f3cc-48fe-8a63-e8f5ba41a842")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6449d789-f3cc-48fe-8a63-e8f5ba41a842")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The VirginMedia item.
            /// </summary>
            [RepositoryItem("dd472150-7887-44de-b6ee-daa70cff6438")]
            public virtual Ranorex.ImgTag VirginMedia
            {
                get
                {
                    return _virginmediaInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The VirginMedia item info.
            /// </summary>
            [RepositoryItemInfo("dd472150-7887-44de-b6ee-daa70cff6438")]
            public virtual VirginMediaInfoClass VirginMediaInfo
            {
                get
                {
                    return _virginmediaInfo;
                }
            }

            /// <summary>
            /// The FindAStore item.
            /// </summary>
            [RepositoryItem("a5750005-6ef7-4f3e-98c3-47ee3a2413ed")]
            public virtual Ranorex.ATag FindAStore
            {
                get
                {
                    return _findastoreInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FindAStore item info.
            /// </summary>
            [RepositoryItemInfo("a5750005-6ef7-4f3e-98c3-47ee3a2413ed")]
            public virtual RepoItemInfo FindAStoreInfo
            {
                get
                {
                    return _findastoreInfo;
                }
            }

            /// <summary>
            /// The ExpandingOurNetwork item.
            /// </summary>
            [RepositoryItem("c0083344-eaba-4085-9513-9840c6dabf9e")]
            public virtual Ranorex.ATag ExpandingOurNetwork
            {
                get
                {
                    return _expandingournetworkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ExpandingOurNetwork item info.
            /// </summary>
            [RepositoryItemInfo("c0083344-eaba-4085-9513-9840c6dabf9e")]
            public virtual RepoItemInfo ExpandingOurNetworkInfo
            {
                get
                {
                    return _expandingournetworkInfo;
                }
            }

            /// <summary>
            /// The ForBusiness item.
            /// </summary>
            [RepositoryItem("c4cbcd82-30c2-4271-8596-10fa591f4520")]
            public virtual Ranorex.ATag ForBusiness
            {
                get
                {
                    return _forbusinessInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ForBusiness item info.
            /// </summary>
            [RepositoryItemInfo("c4cbcd82-30c2-4271-8596-10fa591f4520")]
            public virtual RepoItemInfo ForBusinessInfo
            {
                get
                {
                    return _forbusinessInfo;
                }
            }

            /// <summary>
            /// The Help item.
            /// </summary>
            [RepositoryItem("729e15b1-2fc9-42c9-996e-6e5e72617efa")]
            public virtual Ranorex.ATag Help
            {
                get
                {
                    return _helpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Help item info.
            /// </summary>
            [RepositoryItemInfo("729e15b1-2fc9-42c9-996e-6e5e72617efa")]
            public virtual RepoItemInfo HelpInfo
            {
                get
                {
                    return _helpInfo;
                }
            }
        }

        /// <summary>
        /// The VirginMediaMyVirginMediaAppFolder folder.
        /// </summary>
        [RepositoryFolder("2d3ecc95-4379-4ad1-9cd7-1ee55a5a99b1")]
        public partial class VirginMediaMyVirginMediaAppFolder : RepoGenBaseFolder
        {
            RxDatabaseTestRepositoryFolders.UnifiedHeaderLevelOneFolder _unifiedheaderlevelone;
            RepoItemInfo _forthehomeInfo;
            RepoItemInfo _forbusinessInfo;

            /// <summary>
            /// Creates a new VirginMediaMyVirginMedia  folder.
            /// </summary>
            public VirginMediaMyVirginMediaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VirginMediaMyVirginMedia", "/dom[@domain='my.virginmedia.com']", parentFolder, 30000, null, false, "2d3ecc95-4379-4ad1-9cd7-1ee55a5a99b1", "")
            {
                _unifiedheaderlevelone = new RxDatabaseTestRepositoryFolders.UnifiedHeaderLevelOneFolder(this);
                _forthehomeInfo = new RepoItemInfo(this, "ForTheHome", ".//div[#'unified-header-level-one']//a[@innertext='For the home']", 30000, null, "b076ffca-6661-42e8-b2fe-79474822fb77");
                _forbusinessInfo = new RepoItemInfo(this, "ForBusiness", ".//div[#'unified-header-level-one']//a[@innertext='For business']", 30000, null, "fff7c40c-2e4a-439c-b825-686a2bd89b1b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2d3ecc95-4379-4ad1-9cd7-1ee55a5a99b1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2d3ecc95-4379-4ad1-9cd7-1ee55a5a99b1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ForTheHome item.
            /// </summary>
            [RepositoryItem("b076ffca-6661-42e8-b2fe-79474822fb77")]
            public virtual Ranorex.ATag ForTheHome
            {
                get
                {
                    return _forthehomeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ForTheHome item info.
            /// </summary>
            [RepositoryItemInfo("b076ffca-6661-42e8-b2fe-79474822fb77")]
            public virtual RepoItemInfo ForTheHomeInfo
            {
                get
                {
                    return _forthehomeInfo;
                }
            }

            /// <summary>
            /// The ForBusiness item.
            /// </summary>
            [RepositoryItem("fff7c40c-2e4a-439c-b825-686a2bd89b1b")]
            public virtual Ranorex.ATag ForBusiness
            {
                get
                {
                    return _forbusinessInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ForBusiness item info.
            /// </summary>
            [RepositoryItemInfo("fff7c40c-2e4a-439c-b825-686a2bd89b1b")]
            public virtual RepoItemInfo ForBusinessInfo
            {
                get
                {
                    return _forbusinessInfo;
                }
            }

            /// <summary>
            /// The UnifiedHeaderLevelOne folder.
            /// </summary>
            [RepositoryFolder("60bd31ca-9569-4d46-aab9-ad24e2b89ac7")]
            public virtual RxDatabaseTestRepositoryFolders.UnifiedHeaderLevelOneFolder UnifiedHeaderLevelOne
            {
                get { return _unifiedheaderlevelone; }
            }
        }

        /// <summary>
        /// The UnifiedHeaderLevelOneFolder folder.
        /// </summary>
        [RepositoryFolder("60bd31ca-9569-4d46-aab9-ad24e2b89ac7")]
        public partial class UnifiedHeaderLevelOneFolder : RepoGenBaseFolder
        {
            RepoItemInfo _expandingournetworkInfo;
            RepoItemInfo _helpInfo;
            RepoItemInfo _myprofileInfo;

            /// <summary>
            /// Creates a new UnifiedHeaderLevelOne  folder.
            /// </summary>
            public UnifiedHeaderLevelOneFolder(RepoGenBaseFolder parentFolder) :
                    base("UnifiedHeaderLevelOne", ".//div[#'unified-header-level-one']", parentFolder, 30000, null, false, "60bd31ca-9569-4d46-aab9-ad24e2b89ac7", "")
            {
                _expandingournetworkInfo = new RepoItemInfo(this, "ExpandingOurNetwork", ".//a[@innertext='Expanding our network']", 30000, null, "d3fdf01c-3ac2-4a8a-ae8b-d0a770a41d32");
                _helpInfo = new RepoItemInfo(this, "Help", "ul[3]//strong[@innertext='Help']", 30000, null, "9ce99ace-fcbc-4d93-a9b2-edda074e75d7");
                _myprofileInfo = new RepoItemInfo(this, "MyProfile", "ul[3]//strong[@innertext='My profile']", 30000, null, "f84e8a6e-dc2b-403f-8d32-be8242fd0206");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("60bd31ca-9569-4d46-aab9-ad24e2b89ac7")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("60bd31ca-9569-4d46-aab9-ad24e2b89ac7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ExpandingOurNetwork item.
            /// </summary>
            [RepositoryItem("d3fdf01c-3ac2-4a8a-ae8b-d0a770a41d32")]
            public virtual Ranorex.ATag ExpandingOurNetwork
            {
                get
                {
                    return _expandingournetworkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ExpandingOurNetwork item info.
            /// </summary>
            [RepositoryItemInfo("d3fdf01c-3ac2-4a8a-ae8b-d0a770a41d32")]
            public virtual RepoItemInfo ExpandingOurNetworkInfo
            {
                get
                {
                    return _expandingournetworkInfo;
                }
            }

            /// <summary>
            /// The Help item.
            /// </summary>
            [RepositoryItem("9ce99ace-fcbc-4d93-a9b2-edda074e75d7")]
            public virtual Ranorex.StrongTag Help
            {
                get
                {
                    return _helpInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The Help item info.
            /// </summary>
            [RepositoryItemInfo("9ce99ace-fcbc-4d93-a9b2-edda074e75d7")]
            public virtual RepoItemInfo HelpInfo
            {
                get
                {
                    return _helpInfo;
                }
            }

            /// <summary>
            /// The MyProfile item.
            /// </summary>
            [RepositoryItem("f84e8a6e-dc2b-403f-8d32-be8242fd0206")]
            public virtual Ranorex.StrongTag MyProfile
            {
                get
                {
                    return _myprofileInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The MyProfile item info.
            /// </summary>
            [RepositoryItemInfo("f84e8a6e-dc2b-403f-8d32-be8242fd0206")]
            public virtual RepoItemInfo MyProfileInfo
            {
                get
                {
                    return _myprofileInfo;
                }
            }
        }

        /// <summary>
        /// The VirginMediaBusinessBusinessAndPubAppFolder folder.
        /// </summary>
        [RepositoryFolder("4182e6ef-4ad1-4039-81f8-5be2df6354a6")]
        public partial class VirginMediaBusinessBusinessAndPubAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clientcaptionInfo;

            /// <summary>
            /// Creates a new VirginMediaBusinessBusinessAndPub  folder.
            /// </summary>
            public VirginMediaBusinessBusinessAndPubAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VirginMediaBusinessBusinessAndPub", "/form[@title~'^Virgin\\ Media\\ Business\\ \\|\\ B']", parentFolder, 30000, null, true, "4182e6ef-4ad1-4039-81f8-5be2df6354a6", "")
            {
                _clientcaptionInfo = new RepoItemInfo(this, "ClientCaption", "element[@class='Client Caption']", 30000, null, "4a1065aa-24c4-4e0e-a5b7-15cf55bf7b19");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4182e6ef-4ad1-4039-81f8-5be2df6354a6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4182e6ef-4ad1-4039-81f8-5be2df6354a6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ClientCaption item.
            /// </summary>
            [RepositoryItem("4a1065aa-24c4-4e0e-a5b7-15cf55bf7b19")]
            public virtual Ranorex.Unknown ClientCaption
            {
                get
                {
                    return _clientcaptionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ClientCaption item info.
            /// </summary>
            [RepositoryItemInfo("4a1065aa-24c4-4e0e-a5b7-15cf55bf7b19")]
            public virtual RepoItemInfo ClientCaptionInfo
            {
                get
                {
                    return _clientcaptionInfo;
                }
            }
        }

        /// <summary>
        /// The VirginMediaOfficialSiteInternetAppFolder folder.
        /// </summary>
        [RepositoryFolder("64541cbd-0120-4185-8052-27ab8d8751d6")]
        public partial class VirginMediaOfficialSiteInternetAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clientcaptionInfo;

            /// <summary>
            /// Creates a new VirginMediaOfficialSiteInternet  folder.
            /// </summary>
            public VirginMediaOfficialSiteInternetAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VirginMediaOfficialSiteInternet", "/form[@title~'^Virgin\\ Media\\ -\\ Official\\ S']", parentFolder, 30000, null, true, "64541cbd-0120-4185-8052-27ab8d8751d6", "")
            {
                _clientcaptionInfo = new RepoItemInfo(this, "ClientCaption", "element[@class='Client Caption']", 30000, null, "5a6d3c5d-1af1-4a78-95a9-4ba6807977ff");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("64541cbd-0120-4185-8052-27ab8d8751d6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("64541cbd-0120-4185-8052-27ab8d8751d6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ClientCaption item.
            /// </summary>
            [RepositoryItem("5a6d3c5d-1af1-4a78-95a9-4ba6807977ff")]
            public virtual Ranorex.Unknown ClientCaption
            {
                get
                {
                    return _clientcaptionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ClientCaption item info.
            /// </summary>
            [RepositoryItemInfo("5a6d3c5d-1af1-4a78-95a9-4ba6807977ff")]
            public virtual RepoItemInfo ClientCaptionInfo
            {
                get
                {
                    return _clientcaptionInfo;
                }
            }
        }

        /// <summary>
        /// The YahooLoginAppFolder folder.
        /// </summary>
        [RepositoryFolder("bca39131-1b42-431e-a5ff-877e444ff632")]
        public partial class YahooLoginAppFolder : RepoGenBaseFolder
        {
            YahooInfoClass _yahooInfo;
            RepoItemInfo _strongtagsignintoInfo;
            RepoItemInfo _loginusernameInfo;
            LoginSigninInfoClass _loginsigninInfo;
            RepoItemInfo _loginpasswdInfo;
            RepoItemInfo _loginsignin1Info;
            RepoItemInfo _looksgoodInfo;

            /// <summary>
            /// Creates a new YahooLogin  folder.
            /// </summary>
            public YahooLoginAppFolder(RepoGenBaseFolder parentFolder) :
                    base("YahooLogin", "/dom[@domain='login.yahoo.com']", parentFolder, 30000, null, false, "bca39131-1b42-431e-a5ff-877e444ff632", "")
            {
                _yahooInfo = new YahooInfoClass(this);
                _strongtagsignintoInfo = new RepoItemInfo(this, "StrongTagSignInTo", "body/div[2]/div[1]/div[1]/div[2]/strong[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ Sign']", 30000, null, "90e5f1d3-4d0c-4b2d-9319-b7b453e48328");
                _loginusernameInfo = new RepoItemInfo(this, "LoginUsername", ".//input[#'login-username']", 30000, null, "c78be513-d70e-4888-826f-716e51553909");
                _loginsigninInfo = new LoginSigninInfoClass(this);
                _loginpasswdInfo = new RepoItemInfo(this, "LoginPasswd", ".//input[#'login-passwd']", 30000, null, "4ca9b548-1d56-4767-9b8f-028c1e7bf7c1");
                _loginsignin1Info = new RepoItemInfo(this, "LoginSignin1", ".//button[#'login-signin']", 30000, null, "e69b68b6-1534-4905-9384-0a73131c2fd3");
                _looksgoodInfo = new RepoItemInfo(this, "LooksGood", ".//div[#'login-body']//form[@action='/account/comm-channel/refresh?display=login&.intl=gb&intl=gb&.lang=en-GB&src=ym&done=https%3A%2F%2Fguce.yahoo.com%2Fconsent%3Fgcrumb%3DD93K-xg%26trapType%3Dlogin%26done%3Dhttps%253A%252F%252Fmail.yahoo.com%252Fd%26src%3Dym&scrumb=VxRMdbJNZ42']/div[2]/button[@innertext='Looks good']", 30000, null, "66cac81a-eab1-4251-bae1-b5f728b3ecf4");
            }

            /// <summary>
            /// The YahooInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("11281bbb-c6db-4012-8678-6a5a3b23bd28")]
            public class YahooInfoClass : RepoItemInfo
            {
                /// <summary>
                /// YahooInfoClass class constructor.
                /// </summary>
                public YahooInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Yahoo", "body/div[1]/?/?/a[@title='Yahoo']/img[@src='https://s.yimg.com/rz/p/yahoo_frontpage_en-US_s_f_p_bestfit_frontpage_2x.png']", 30000, null, "11281bbb-c6db-4012-8678-6a5a3b23bd28")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("622ab164-685f-4a0b-9e65-fe5c4b3ac794")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("622ab164-685f-4a0b-9e65-fe5c4b3ac794");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("622ab164-685f-4a0b-9e65-fe5c4b3ac794")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("622ab164-685f-4a0b-9e65-fe5c4b3ac794", cropRect);
                }
            }

            /// <summary>
            /// The LoginSigninInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("da30ae23-2ca2-4b00-bfb7-3d481b4d75d3")]
            public class LoginSigninInfoClass : RepoItemInfo
            {
                /// <summary>
                /// LoginSigninInfoClass class constructor.
                /// </summary>
                public LoginSigninInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "LoginSignin", ".//input[#'login-signin']", 30000, null, "da30ae23-2ca2-4b00-bfb7-3d481b4d75d3")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("8e311376-70e0-4c1d-b25a-83ed68191a2f")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("8e311376-70e0-4c1d-b25a-83ed68191a2f");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("8e311376-70e0-4c1d-b25a-83ed68191a2f")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("8e311376-70e0-4c1d-b25a-83ed68191a2f", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bca39131-1b42-431e-a5ff-877e444ff632")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bca39131-1b42-431e-a5ff-877e444ff632")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Yahoo item.
            /// </summary>
            [RepositoryItem("11281bbb-c6db-4012-8678-6a5a3b23bd28")]
            public virtual Ranorex.ImgTag Yahoo
            {
                get
                {
                    return _yahooInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Yahoo item info.
            /// </summary>
            [RepositoryItemInfo("11281bbb-c6db-4012-8678-6a5a3b23bd28")]
            public virtual YahooInfoClass YahooInfo
            {
                get
                {
                    return _yahooInfo;
                }
            }

            /// <summary>
            /// The StrongTagSignInTo item.
            /// </summary>
            [RepositoryItem("90e5f1d3-4d0c-4b2d-9319-b7b453e48328")]
            public virtual Ranorex.StrongTag StrongTagSignInTo
            {
                get
                {
                    return _strongtagsignintoInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The StrongTagSignInTo item info.
            /// </summary>
            [RepositoryItemInfo("90e5f1d3-4d0c-4b2d-9319-b7b453e48328")]
            public virtual RepoItemInfo StrongTagSignInToInfo
            {
                get
                {
                    return _strongtagsignintoInfo;
                }
            }

            /// <summary>
            /// The LoginUsername item.
            /// </summary>
            [RepositoryItem("c78be513-d70e-4888-826f-716e51553909")]
            public virtual Ranorex.InputTag LoginUsername
            {
                get
                {
                    return _loginusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginUsername item info.
            /// </summary>
            [RepositoryItemInfo("c78be513-d70e-4888-826f-716e51553909")]
            public virtual RepoItemInfo LoginUsernameInfo
            {
                get
                {
                    return _loginusernameInfo;
                }
            }

            /// <summary>
            /// The LoginSignin item.
            /// </summary>
            [RepositoryItem("da30ae23-2ca2-4b00-bfb7-3d481b4d75d3")]
            public virtual Ranorex.InputTag LoginSignin
            {
                get
                {
                    return _loginsigninInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginSignin item info.
            /// </summary>
            [RepositoryItemInfo("da30ae23-2ca2-4b00-bfb7-3d481b4d75d3")]
            public virtual LoginSigninInfoClass LoginSigninInfo
            {
                get
                {
                    return _loginsigninInfo;
                }
            }

            /// <summary>
            /// The LoginPasswd item.
            /// </summary>
            [RepositoryItem("4ca9b548-1d56-4767-9b8f-028c1e7bf7c1")]
            public virtual Ranorex.InputTag LoginPasswd
            {
                get
                {
                    return _loginpasswdInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginPasswd item info.
            /// </summary>
            [RepositoryItemInfo("4ca9b548-1d56-4767-9b8f-028c1e7bf7c1")]
            public virtual RepoItemInfo LoginPasswdInfo
            {
                get
                {
                    return _loginpasswdInfo;
                }
            }

            /// <summary>
            /// The LoginSignin1 item.
            /// </summary>
            [RepositoryItem("e69b68b6-1534-4905-9384-0a73131c2fd3")]
            public virtual Ranorex.ButtonTag LoginSignin1
            {
                get
                {
                    return _loginsignin1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The LoginSignin1 item info.
            /// </summary>
            [RepositoryItemInfo("e69b68b6-1534-4905-9384-0a73131c2fd3")]
            public virtual RepoItemInfo LoginSignin1Info
            {
                get
                {
                    return _loginsignin1Info;
                }
            }

            /// <summary>
            /// The LooksGood item.
            /// </summary>
            [RepositoryItem("66cac81a-eab1-4251-bae1-b5f728b3ecf4")]
            public virtual Ranorex.ButtonTag LooksGood
            {
                get
                {
                    return _looksgoodInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The LooksGood item info.
            /// </summary>
            [RepositoryItemInfo("66cac81a-eab1-4251-bae1-b5f728b3ecf4")]
            public virtual RepoItemInfo LooksGoodInfo
            {
                get
                {
                    return _looksgoodInfo;
                }
            }
        }

        /// <summary>
        /// The YahooMailAppFolder folder.
        /// </summary>
        [RepositoryFolder("ead32e73-8d7a-44f2-a791-3bc5fe8ae9e4")]
        public partial class YahooMailAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _continueInfo;
            RepoItemInfo _letsgoInfo;
            RepoItemInfo _signoutInfo;

            /// <summary>
            /// Creates a new YahooMail  folder.
            /// </summary>
            public YahooMailAppFolder(RepoGenBaseFolder parentFolder) :
                    base("YahooMail", "/dom[@domain='mail.yahoo.com']", parentFolder, 30000, null, false, "ead32e73-8d7a-44f2-a791-3bc5fe8ae9e4", "")
            {
                _continueInfo = new RepoItemInfo(this, "Continue", ".//td[#'dt-content']//ul/?/?/a[@href~'^https://mail\\.yahoo\\.com/b/']/span[@innertext='Continue']", 30000, null, "bacb0b6b-6432-4c54-a27f-3b9266f21c38");
                _letsgoInfo = new RepoItemInfo(this, "LetsGo", ".//div[#'app']/div[1]/div//a[@innertext='Let''s go!']", 30000, null, "3bc10033-6995-4985-bcdb-121ff9856ee5");
                _signoutInfo = new RepoItemInfo(this, "SignOut", ".//div[#'app']/div[1]/table[1]/tbody/tr[1]/td[3]/form[@name='form']/a[@innertext='Sign Out']", 30000, null, "7bbdef37-b9ce-4200-8e8d-a92408ec9260");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ead32e73-8d7a-44f2-a791-3bc5fe8ae9e4")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ead32e73-8d7a-44f2-a791-3bc5fe8ae9e4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("bacb0b6b-6432-4c54-a27f-3b9266f21c38")]
            public virtual Ranorex.SpanTag Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("bacb0b6b-6432-4c54-a27f-3b9266f21c38")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The LetsGo item.
            /// </summary>
            [RepositoryItem("3bc10033-6995-4985-bcdb-121ff9856ee5")]
            public virtual Ranorex.ATag LetsGo
            {
                get
                {
                    return _letsgoInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LetsGo item info.
            /// </summary>
            [RepositoryItemInfo("3bc10033-6995-4985-bcdb-121ff9856ee5")]
            public virtual RepoItemInfo LetsGoInfo
            {
                get
                {
                    return _letsgoInfo;
                }
            }

            /// <summary>
            /// The SignOut item.
            /// </summary>
            [RepositoryItem("7bbdef37-b9ce-4200-8e8d-a92408ec9260")]
            public virtual Ranorex.ATag SignOut
            {
                get
                {
                    return _signoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SignOut item info.
            /// </summary>
            [RepositoryItemInfo("7bbdef37-b9ce-4200-8e8d-a92408ec9260")]
            public virtual RepoItemInfo SignOutInfo
            {
                get
                {
                    return _signoutInfo;
                }
            }
        }

        /// <summary>
        /// The YahooUKNewsEmailAndSearchInteAppFolder folder.
        /// </summary>
        [RepositoryFolder("471d34d2-0e13-4351-8740-590f8401d9b9")]
        public partial class YahooUKNewsEmailAndSearchInteAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clientcaptionInfo;

            /// <summary>
            /// Creates a new YahooUKNewsEmailAndSearchInte  folder.
            /// </summary>
            public YahooUKNewsEmailAndSearchInteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("YahooUKNewsEmailAndSearchInte", "/form[@title~'^Yahoo\\ UK\\ \\|\\ News,\\ email\\ an']", parentFolder, 30000, null, true, "471d34d2-0e13-4351-8740-590f8401d9b9", "")
            {
                _clientcaptionInfo = new RepoItemInfo(this, "ClientCaption", "element[@class='Client Caption']", 30000, null, "b14e0fb6-6826-4ef6-8e48-bfc813f2fdb5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("471d34d2-0e13-4351-8740-590f8401d9b9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("471d34d2-0e13-4351-8740-590f8401d9b9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ClientCaption item.
            /// </summary>
            [RepositoryItem("b14e0fb6-6826-4ef6-8e48-bfc813f2fdb5")]
            public virtual Ranorex.Unknown ClientCaption
            {
                get
                {
                    return _clientcaptionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ClientCaption item info.
            /// </summary>
            [RepositoryItemInfo("b14e0fb6-6826-4ef6-8e48-bfc813f2fdb5")]
            public virtual RepoItemInfo ClientCaptionInfo
            {
                get
                {
                    return _clientcaptionInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}