///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDatabaseTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDatabaseTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("558d6956-a12d-4102-ae72-579bfe35899a")]
    public partial class RxDatabaseTestRepository : RepoGenBaseFolder
    {
        static RxDatabaseTestRepository instance = new RxDatabaseTestRepository();
        RxDatabaseTestRepositoryFolders.VirginMediaOfficialSiteAppFolder _virginmediaofficialsite;
        RxDatabaseTestRepositoryFolders.VirginMediaMyVirginMediaAppFolder _virginmediamyvirginmedia;
        RxDatabaseTestRepositoryFolders.VirginMediaBusinessBusinessAndPubAppFolder _virginmediabusinessbusinessandpub;

        /// <summary>
        /// Gets the singleton class instance representing the RxDatabaseTestRepository element repository.
        /// </summary>
        [RepositoryFolder("558d6956-a12d-4102-ae72-579bfe35899a")]
        public static RxDatabaseTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDatabaseTestRepository() 
            : base("RxDatabaseTestRepository", "/", null, 0, false, "558d6956-a12d-4102-ae72-579bfe35899a", ".\\RepositoryImages\\RxDatabaseTestRepository558d6956.rximgres")
        {
            _virginmediaofficialsite = new RxDatabaseTestRepositoryFolders.VirginMediaOfficialSiteAppFolder(this);
            _virginmediamyvirginmedia = new RxDatabaseTestRepositoryFolders.VirginMediaMyVirginMediaAppFolder(this);
            _virginmediabusinessbusinessandpub = new RxDatabaseTestRepositoryFolders.VirginMediaBusinessBusinessAndPubAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("558d6956-a12d-4102-ae72-579bfe35899a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The VirginMediaOfficialSite folder.
        /// </summary>
        [RepositoryFolder("da0e99d9-f0ce-4ba9-ba9a-8c9792248f87")]
        public virtual RxDatabaseTestRepositoryFolders.VirginMediaOfficialSiteAppFolder VirginMediaOfficialSite
        {
            get { return _virginmediaofficialsite; }
        }

        /// <summary>
        /// The VirginMediaMyVirginMedia folder.
        /// </summary>
        [RepositoryFolder("2d3ecc95-4379-4ad1-9cd7-1ee55a5a99b1")]
        public virtual RxDatabaseTestRepositoryFolders.VirginMediaMyVirginMediaAppFolder VirginMediaMyVirginMedia
        {
            get { return _virginmediamyvirginmedia; }
        }

        /// <summary>
        /// The VirginMediaBusinessBusinessAndPub folder.
        /// </summary>
        [RepositoryFolder("4182e6ef-4ad1-4039-81f8-5be2df6354a6")]
        public virtual RxDatabaseTestRepositoryFolders.VirginMediaBusinessBusinessAndPubAppFolder VirginMediaBusinessBusinessAndPub
        {
            get { return _virginmediabusinessbusinessandpub; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class RxDatabaseTestRepositoryFolders
    {
        /// <summary>
        /// The VirginMediaOfficialSiteAppFolder folder.
        /// </summary>
        [RepositoryFolder("da0e99d9-f0ce-4ba9-ba9a-8c9792248f87")]
        public partial class VirginMediaOfficialSiteAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _myvirginmediaInfo;

            /// <summary>
            /// Creates a new VirginMediaOfficialSite  folder.
            /// </summary>
            public VirginMediaOfficialSiteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VirginMediaOfficialSite", "/dom[@domain='www.virginmedia.com']", parentFolder, 30000, null, false, "da0e99d9-f0ce-4ba9-ba9a-8c9792248f87", "")
            {
                _myvirginmediaInfo = new RepoItemInfo(this, "MyVirginMedia", ".//div[#'unified-header']/div/div/div[2]/div[1]/div[3]/ul/li[2]/a[@innertext='My Virgin Media    ']", 30000, null, "142d9fa3-95fb-46ac-8c7e-b261e4938345");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("da0e99d9-f0ce-4ba9-ba9a-8c9792248f87")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("da0e99d9-f0ce-4ba9-ba9a-8c9792248f87")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MyVirginMedia item.
            /// </summary>
            [RepositoryItem("142d9fa3-95fb-46ac-8c7e-b261e4938345")]
            public virtual Ranorex.ATag MyVirginMedia
            {
                get
                {
                    return _myvirginmediaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MyVirginMedia item info.
            /// </summary>
            [RepositoryItemInfo("142d9fa3-95fb-46ac-8c7e-b261e4938345")]
            public virtual RepoItemInfo MyVirginMediaInfo
            {
                get
                {
                    return _myvirginmediaInfo;
                }
            }
        }

        /// <summary>
        /// The VirginMediaMyVirginMediaAppFolder folder.
        /// </summary>
        [RepositoryFolder("2d3ecc95-4379-4ad1-9cd7-1ee55a5a99b1")]
        public partial class VirginMediaMyVirginMediaAppFolder : RepoGenBaseFolder
        {
            RxDatabaseTestRepositoryFolders.UnifiedHeaderLevelOneFolder _unifiedheaderlevelone;
            RepoItemInfo _forthehomeInfo;
            RepoItemInfo _forbusinessInfo;

            /// <summary>
            /// Creates a new VirginMediaMyVirginMedia  folder.
            /// </summary>
            public VirginMediaMyVirginMediaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VirginMediaMyVirginMedia", "/dom[@domain='my.virginmedia.com']", parentFolder, 30000, null, false, "2d3ecc95-4379-4ad1-9cd7-1ee55a5a99b1", "")
            {
                _unifiedheaderlevelone = new RxDatabaseTestRepositoryFolders.UnifiedHeaderLevelOneFolder(this);
                _forthehomeInfo = new RepoItemInfo(this, "ForTheHome", ".//div[#'unified-header-level-one']//a[@innertext='For the home']", 30000, null, "b076ffca-6661-42e8-b2fe-79474822fb77");
                _forbusinessInfo = new RepoItemInfo(this, "ForBusiness", ".//div[#'unified-header-level-one']//a[@innertext='For business']", 30000, null, "fff7c40c-2e4a-439c-b825-686a2bd89b1b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2d3ecc95-4379-4ad1-9cd7-1ee55a5a99b1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2d3ecc95-4379-4ad1-9cd7-1ee55a5a99b1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ForTheHome item.
            /// </summary>
            [RepositoryItem("b076ffca-6661-42e8-b2fe-79474822fb77")]
            public virtual Ranorex.ATag ForTheHome
            {
                get
                {
                    return _forthehomeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ForTheHome item info.
            /// </summary>
            [RepositoryItemInfo("b076ffca-6661-42e8-b2fe-79474822fb77")]
            public virtual RepoItemInfo ForTheHomeInfo
            {
                get
                {
                    return _forthehomeInfo;
                }
            }

            /// <summary>
            /// The ForBusiness item.
            /// </summary>
            [RepositoryItem("fff7c40c-2e4a-439c-b825-686a2bd89b1b")]
            public virtual Ranorex.ATag ForBusiness
            {
                get
                {
                    return _forbusinessInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ForBusiness item info.
            /// </summary>
            [RepositoryItemInfo("fff7c40c-2e4a-439c-b825-686a2bd89b1b")]
            public virtual RepoItemInfo ForBusinessInfo
            {
                get
                {
                    return _forbusinessInfo;
                }
            }

            /// <summary>
            /// The UnifiedHeaderLevelOne folder.
            /// </summary>
            [RepositoryFolder("60bd31ca-9569-4d46-aab9-ad24e2b89ac7")]
            public virtual RxDatabaseTestRepositoryFolders.UnifiedHeaderLevelOneFolder UnifiedHeaderLevelOne
            {
                get { return _unifiedheaderlevelone; }
            }
        }

        /// <summary>
        /// The UnifiedHeaderLevelOneFolder folder.
        /// </summary>
        [RepositoryFolder("60bd31ca-9569-4d46-aab9-ad24e2b89ac7")]
        public partial class UnifiedHeaderLevelOneFolder : RepoGenBaseFolder
        {
            RepoItemInfo _expandingournetworkInfo;
            RepoItemInfo _helpInfo;
            RepoItemInfo _myprofileInfo;

            /// <summary>
            /// Creates a new UnifiedHeaderLevelOne  folder.
            /// </summary>
            public UnifiedHeaderLevelOneFolder(RepoGenBaseFolder parentFolder) :
                    base("UnifiedHeaderLevelOne", ".//div[#'unified-header-level-one']", parentFolder, 30000, null, false, "60bd31ca-9569-4d46-aab9-ad24e2b89ac7", "")
            {
                _expandingournetworkInfo = new RepoItemInfo(this, "ExpandingOurNetwork", ".//a[@innertext='Expanding our network']", 30000, null, "d3fdf01c-3ac2-4a8a-ae8b-d0a770a41d32");
                _helpInfo = new RepoItemInfo(this, "Help", "ul[3]//strong[@innertext='Help']", 30000, null, "9ce99ace-fcbc-4d93-a9b2-edda074e75d7");
                _myprofileInfo = new RepoItemInfo(this, "MyProfile", "ul[3]//strong[@innertext='My profile']", 30000, null, "f84e8a6e-dc2b-403f-8d32-be8242fd0206");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("60bd31ca-9569-4d46-aab9-ad24e2b89ac7")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("60bd31ca-9569-4d46-aab9-ad24e2b89ac7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ExpandingOurNetwork item.
            /// </summary>
            [RepositoryItem("d3fdf01c-3ac2-4a8a-ae8b-d0a770a41d32")]
            public virtual Ranorex.ATag ExpandingOurNetwork
            {
                get
                {
                    return _expandingournetworkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ExpandingOurNetwork item info.
            /// </summary>
            [RepositoryItemInfo("d3fdf01c-3ac2-4a8a-ae8b-d0a770a41d32")]
            public virtual RepoItemInfo ExpandingOurNetworkInfo
            {
                get
                {
                    return _expandingournetworkInfo;
                }
            }

            /// <summary>
            /// The Help item.
            /// </summary>
            [RepositoryItem("9ce99ace-fcbc-4d93-a9b2-edda074e75d7")]
            public virtual Ranorex.StrongTag Help
            {
                get
                {
                    return _helpInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The Help item info.
            /// </summary>
            [RepositoryItemInfo("9ce99ace-fcbc-4d93-a9b2-edda074e75d7")]
            public virtual RepoItemInfo HelpInfo
            {
                get
                {
                    return _helpInfo;
                }
            }

            /// <summary>
            /// The MyProfile item.
            /// </summary>
            [RepositoryItem("f84e8a6e-dc2b-403f-8d32-be8242fd0206")]
            public virtual Ranorex.StrongTag MyProfile
            {
                get
                {
                    return _myprofileInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The MyProfile item info.
            /// </summary>
            [RepositoryItemInfo("f84e8a6e-dc2b-403f-8d32-be8242fd0206")]
            public virtual RepoItemInfo MyProfileInfo
            {
                get
                {
                    return _myprofileInfo;
                }
            }
        }

        /// <summary>
        /// The VirginMediaBusinessBusinessAndPubAppFolder folder.
        /// </summary>
        [RepositoryFolder("4182e6ef-4ad1-4039-81f8-5be2df6354a6")]
        public partial class VirginMediaBusinessBusinessAndPubAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clientcaptionInfo;

            /// <summary>
            /// Creates a new VirginMediaBusinessBusinessAndPub  folder.
            /// </summary>
            public VirginMediaBusinessBusinessAndPubAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VirginMediaBusinessBusinessAndPub", "/form[@title~'^Virgin\\ Media\\ Business\\ \\|\\ B']", parentFolder, 30000, null, true, "4182e6ef-4ad1-4039-81f8-5be2df6354a6", "")
            {
                _clientcaptionInfo = new RepoItemInfo(this, "ClientCaption", "element[@class='Client Caption']", 30000, null, "4a1065aa-24c4-4e0e-a5b7-15cf55bf7b19");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4182e6ef-4ad1-4039-81f8-5be2df6354a6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4182e6ef-4ad1-4039-81f8-5be2df6354a6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ClientCaption item.
            /// </summary>
            [RepositoryItem("4a1065aa-24c4-4e0e-a5b7-15cf55bf7b19")]
            public virtual Ranorex.Unknown ClientCaption
            {
                get
                {
                    return _clientcaptionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ClientCaption item info.
            /// </summary>
            [RepositoryItemInfo("4a1065aa-24c4-4e0e-a5b7-15cf55bf7b19")]
            public virtual RepoItemInfo ClientCaptionInfo
            {
                get
                {
                    return _clientcaptionInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}