///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDatabaseTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidatePage recording.
    /// </summary>
    [TestModule("6a157bd6-6567-47a9-8248-4a08244faf2d", ModuleType.Recording, 1)]
    public partial class ValidatePage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RxDatabaseTestRepository repository.
        /// </summary>
        public static RxDatabaseTestRepository repo = RxDatabaseTestRepository.Instance;

        static ValidatePage instance = new ValidatePage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidatePage()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidatePage Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.virginmedia.com/' with browser 'IE' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://www.virginmedia.com/", "IE", "", false, false, false, false, false);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(1));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='My Virgin Media\n    ') on item 'VirginMediaOfficialSite.MyVirginMedia'.", repo.VirginMediaOfficialSite.MyVirginMediaInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.VirginMediaOfficialSite.MyVirginMediaInfo, "InnerText", "My Virgin Media\n    ");
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VirginMediaOfficialSite.MyVirginMedia' at 64;15.", repo.VirginMediaOfficialSite.MyVirginMediaInfo, new RecordItemIndex(4));
            repo.VirginMediaOfficialSite.MyVirginMedia.Click("64;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(5));
            Delay.Duration(30000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Help') on item 'VirginMediaMyVirginMedia.UnifiedHeaderLevelOne.Help'.", repo.VirginMediaMyVirginMedia.UnifiedHeaderLevelOne.HelpInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.VirginMediaMyVirginMedia.UnifiedHeaderLevelOne.HelpInfo, "InnerText", "Help");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Expanding our network\n') on item 'VirginMediaMyVirginMedia.UnifiedHeaderLevelOne.ExpandingOurNetwork'.", repo.VirginMediaMyVirginMedia.UnifiedHeaderLevelOne.ExpandingOurNetworkInfo, new RecordItemIndex(7));
            Validate.Attribute(repo.VirginMediaMyVirginMedia.UnifiedHeaderLevelOne.ExpandingOurNetworkInfo, "InnerText", "Expanding our network\n");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='For the home\n') on item 'VirginMediaMyVirginMedia.ForTheHome'.", repo.VirginMediaMyVirginMedia.ForTheHomeInfo, new RecordItemIndex(8));
            //Validate.Attribute(repo.VirginMediaMyVirginMedia.ForTheHomeInfo, "InnerText", "For the home\n");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://store.virginmedia.com/index.html') on item 'VirginMediaMyVirginMedia.ForTheHome'.", repo.VirginMediaMyVirginMedia.ForTheHomeInfo, new RecordItemIndex(9));
            //Validate.Attribute(repo.VirginMediaMyVirginMedia.ForTheHomeInfo, "Href", "https://store.virginmedia.com/index.html");
            //Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VirginMediaMyVirginMedia.ForBusiness' at 64;20.", repo.VirginMediaMyVirginMedia.ForBusinessInfo, new RecordItemIndex(11));
            repo.VirginMediaMyVirginMedia.ForBusiness.Click("64;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 15s.", new RecordItemIndex(12));
            Delay.Duration(15000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VirginMediaBusinessBusinessAndPub.ClientCaption' at 1881;24.", repo.VirginMediaBusinessBusinessAndPub.ClientCaptionInfo, new RecordItemIndex(14));
            repo.VirginMediaBusinessBusinessAndPub.ClientCaption.Click("1881;24");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
