///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDatabaseTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The YahooMail recording.
    /// </summary>
    [TestModule("2f8b24b0-f8e4-464e-b897-e8b3f8e242b3", ModuleType.Recording, 1)]
    public partial class YahooMail : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RxDatabaseTestRepository repository.
        /// </summary>
        public static RxDatabaseTestRepository repo = RxDatabaseTestRepository.Instance;

        static YahooMail instance = new YahooMail();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public YahooMail()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static YahooMail Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'mail.yahoo.com' with browser 'IE' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("mail.yahoo.com", "IE", "", false, false, false, false, false);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='https://s.yimg.com/rz/p/yahoo_frontpage_en-US_s_f_p_bestfit_frontpage_2x.png') on item 'YahooLogin.Yahoo'.", repo.YahooLogin.YahooInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.YahooLogin.YahooInfo, "Src", "https://s.yimg.com/rz/p/yahoo_frontpage_en-US_s_f_p_bestfit_frontpage_2x.png");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=150,Height=45}) on item 'YahooLogin.Yahoo'.", repo.YahooLogin.YahooInfo, new RecordItemIndex(2));
            //Validate.ContainsImage(repo.YahooLogin.YahooInfo, Yahoo_Screenshot1, Yahoo_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\n                    Sign in to Yahoo Mail\n                ') on item 'YahooLogin.StrongTagSignInTo'.", repo.YahooLogin.StrongTagSignInToInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.YahooLogin.StrongTagSignInToInfo, "InnerText", "\n                    Sign in to Yahoo Mail\n                ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='login-username') on item 'YahooLogin.LoginUsername'.", repo.YahooLogin.LoginUsernameInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.YahooLogin.LoginUsernameInfo, "Id", "login-username");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='input') on item 'YahooLogin.LoginUsername'.", repo.YahooLogin.LoginUsernameInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.YahooLogin.LoginUsernameInfo, "TagName", "input");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'YahooLogin.LoginUsername' at 70;31.", repo.YahooLogin.LoginUsernameInfo, new RecordItemIndex(7));
            repo.YahooLogin.LoginUsername.MoveTo("70;31");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'kayshakthy' with focus on 'YahooLogin.LoginUsername'.", repo.YahooLogin.LoginUsernameInfo, new RecordItemIndex(8));
            repo.YahooLogin.LoginUsername.PressKeys("kayshakthy");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='login-signin') on item 'YahooLogin.LoginSignin'.", repo.YahooLogin.LoginSigninInfo, new RecordItemIndex(9));
            Validate.Attribute(repo.YahooLogin.LoginSigninInfo, "Id", "login-signin");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='input') on item 'YahooLogin.LoginSignin'.", repo.YahooLogin.LoginSigninInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.YahooLogin.LoginSigninInfo, "TagName", "input");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Next') on item 'YahooLogin.LoginSignin'.", repo.YahooLogin.LoginSigninInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.YahooLogin.LoginSigninInfo, "Value", "Next");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=360,Height=52}) on item 'YahooLogin.LoginSignin'.", repo.YahooLogin.LoginSigninInfo, new RecordItemIndex(12));
            Validate.ContainsImage(repo.YahooLogin.LoginSigninInfo, LoginSignin_Screenshot1, LoginSignin_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'YahooLogin.LoginSignin' at 194;23.", repo.YahooLogin.LoginSigninInfo, new RecordItemIndex(13));
            repo.YahooLogin.LoginSignin.DoubleClick("194;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YahooLogin.LoginPasswd' at 107;32.", repo.YahooLogin.LoginPasswdInfo, new RecordItemIndex(14));
            repo.YahooLogin.LoginPasswd.Click("107;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}K{LShiftKey up}iru{LShiftKey down}${LShiftKey up}10306' with focus on 'YahooLogin.LoginPasswd'.", repo.YahooLogin.LoginPasswdInfo, new RecordItemIndex(15));
            repo.YahooLogin.LoginPasswd.PressKeys("{LShiftKey down}K{LShiftKey up}iru{LShiftKey down}${LShiftKey up}10306");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YahooLogin.LoginSignin1' at 234;27.", repo.YahooLogin.LoginSignin1Info, new RecordItemIndex(16));
            repo.YahooLogin.LoginSignin1.Click("234;27");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YahooLogin.LooksGood' at 251;21.", repo.YahooLogin.LooksGoodInfo, new RecordItemIndex(17));
            //repo.YahooLogin.LooksGood.Click("251;21");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YahooMail.Continue' at 30;6.", repo.YahooMail.ContinueInfo, new RecordItemIndex(18));
            //repo.YahooMail.Continue.Click("30;6");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YahooMail.LetsGo' at 170;27.", repo.YahooMail.LetsGoInfo, new RecordItemIndex(19));
            //repo.YahooMail.LetsGo.Click("170;27");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Sign Out') on item 'YahooMail.SignOut'.", repo.YahooMail.SignOutInfo, new RecordItemIndex(20));
            Validate.Attribute(repo.YahooMail.SignOutInfo, "InnerText", "Sign Out");
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "KAYSHAKTHY Yahoo Mail", null, false, new RecordItemIndex(21));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YahooMail.SignOut' at 36;15.", repo.YahooMail.SignOutInfo, new RecordItemIndex(22));
            repo.YahooMail.SignOut.Click("36;15");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YahooUKNewsEmailAndSearchInte.ClientCaption' at 1888;26.", repo.YahooUKNewsEmailAndSearchInte.ClientCaptionInfo, new RecordItemIndex(23));
            //repo.YahooUKNewsEmailAndSearchInte.ClientCaption.Click("1888;26");
            //Delay.Milliseconds(200);
            
            closeBrowser();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage Yahoo_Screenshot1
        { get { return repo.YahooLogin.YahooInfo.GetScreenshot1(new Rectangle(0, 0, 150, 45)); } }

        Imaging.FindOptions Yahoo_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage LoginSignin_Screenshot1
        { get { return repo.YahooLogin.LoginSigninInfo.GetScreenshot1(new Rectangle(0, 0, 360, 52)); } }

        Imaging.FindOptions LoginSignin_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
