///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace RxDatabaseTest
{
    public partial class YahooMail
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void closeBrowser()
        {
        	Report.Info("Inside CloseBrowser() " );
			IList<Ranorex.WebDocument> webList = Host.Local.Find<Ranorex.WebDocument>("/dom[@domain='mail.yahoo.com']");        	
			Report.Info(webList.Count.ToString());
			foreach (Ranorex.WebDocument webdoc in webList)
			{  
//				Report.Info(webdoc.GetHtml());
			    webdoc.Close();
			    Report.Success("Browser Closed Successfully");
			}
			IList<Ranorex.WebDocument> webList1 = Host.Local.Find<Ranorex.WebDocument>("/dom[@domain='uk.yahoo.com']");
			Report.Info(webList1.Count.ToString());
			foreach (Ranorex.WebDocument webdoc1 in webList1)
			{  
				Report.Info(webdoc1.GetPath().ToString());
			    webdoc1.Close();
			    Report.Success("Browser Closed Successfully !");
			}			
//			Report.Info("Before  FindSingle() " );
//			Ranorex.WebDocument doc = Host.Local.FindSingle("/form[@title~'^Yahoo\ UK\ \|\ News,\ email\ an']");
//			doc.Close();
//			IList<Form> forms = Host.Local.Find<Form>(String.Format("/form[@processname='{0}']", BrowserManager.GetProcessName("IE")));
//			IList<Form> forms = Host.Local.Find<Form>(String.Format("/form[@title~'^Yahoo\ UK\ \|\ News,\ email\ an']", BrowserManager.GetProcessName(browserType)));
//			foreach (Form f in forms)
//			{
//			f.Close();
//			}
			
        }

    }
}